### ISSUE TITLE
RSS description not escaped

### ISSUE THREAD

**Issue by jendib** [ACRA/acra-storage#8]
I have this kind of data in the RSS feed:

```
<description>
<p>app_version: 1.3.3</p>
<p>android_version: 4.4.2</p>
<p>device: LGE google Nexus 4</p>
<p>crash line: android.view.InflateException: Binary XML file line #1: Error inflating class <unknown> at com.sismics.reader.ui.adapter.SubscriptionAdapter.getView(SubscriptionAdapter.java:86)</p>
</description>
```

As you can see, there is a fake `<unknown>` tag in the error generated by Android, which causes the feed to be invalid.
The content of `<description>` needs to be escaped.

**Comment by halkeye** [comment]
https://github.com/ACRA/acra-storage/blob/master/lists/rss.js <-- looks like nothing is escaped.

If @KevinGaudin doesn't get to it first, I'll try to get my dev env setup again tonight, It looks like an easy one to try and get back into it.

**Comment by jendib** [comment]
Great thank you!

**Comment by jendib** [comment]
This is great, thank you very much for both commits :+1:

**Comment by jendib** [comment]
Hmm, it seems it's not quite over, the title needs to be escaped too:

```
<title>
  android.view.InflateException: Binary XML file line #1: Error inflating class <unknown> : at
  com.sismics.reader.ui.adapter.SubscriptionAdapter.getView(SubscriptionAdapter.java:86)
</title>
```

**Comment by halkeye** [comment]
boo. Would you be up for throwing up a test record that doesn't work so I can test easier?

**Comment by jendib** [comment]
Do you have an email address? There is some sensitive data in it :)

**Comment by halkeye** [comment]
yea sure, halkeye@gmail.com works fine

**Comment by halkeye** [comment]
should this be closed before its merged?
